name: Keep Supabase Alive

on:
  schedule:
    # Berjalan setiap hari Minggu dan Kamis jam 05:00 UTC (12:00 WIB)
    - cron: '0 5 * * 0,4'
  workflow_dispatch: # Memungkinkan Anda menjalankannya secara manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/index" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
